/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stm32f103x6.h"
#include "Stm32F103C6_GPIO_Driver.h"
#include "lcd.h"
#include "keypad.h"
#include "sevensegment.h"

/*void clock_init()
{
	//GPIOA clock enable
	GPIOA_CLCK_EN();
	//GPIOB clock enable
	GPIOB_CLCK_EN();

}
void GPIO_init(){
	GPIO_PinConfig_t pinCnfg;
	//for PA pin1 to be floating input
	pinCnfg.GPIO_PinNumber = GPIO_PIN_1;
	pinCnfg.GPIO_Mode = GPIO_MODE_FLO_IN;
	MCAL_GPIO_Init(GPIOA,&pinCnfg);

	//for PB pin1 to be output push/pull mode
	pinCnfg.GPIO_PinNumber = GPIO_PIN_1;
	pinCnfg.GPIO_Mode = GPIO_MODE_OUT_PP;
	pinCnfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB,&pinCnfg);
	//for PA pin13 to be floating input
	pinCnfg.GPIO_PinNumber = GPIO_PIN_13;
	pinCnfg.GPIO_Mode = GPIO_MODE_FLO_IN;
	MCAL_GPIO_Init(GPIOA,&pinCnfg);
	//for PB pin13 to be output push/pull mode
	pinCnfg.GPIO_PinNumber = GPIO_PIN_13;
	pinCnfg.GPIO_Mode = GPIO_MODE_OUT_PP;
	pinCnfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB,&pinCnfg);

}

void my_wait(int x)
{
	unsigned int i,j;
	for (i=0 ; i<x ;i++)
		for (j=0 ; j<255 ;j++);

}*/
void clock_init()
{
	//GPIO clock enable
	GPIOA_CLCK_EN();
	GPIOB_CLCK_EN();

}
void app_init()
{
	s_LCD_Config_t LCD_config;
	LCD_config.e_DispCtrl	= ON_DISP | ON_BLINK | ON_CURSOR ;
	LCD_config.e_EntryMode	= NOSHIFT_INCREMENT;
	LCD_config.e_FuncSet	= EIGHT_BIT_MODE_2LINE_10DOTS;
	LCD_init(&LCD_config);
	sevensegment_init();

}





int main(void)
{
	/*clock_init();
	GPIO_init();

	while(1)
		{
			//PA1 >> connected external PUR
			if(MCAL_GPIO_ReadPIN(GPIOA, GPIO_PIN_1) == 0) //press
			{
				MCAL_GPIO_TogglePIN(GPIOB, GPIO_PIN_1);
				while(MCAL_GPIO_ReadPIN(GPIOA, GPIO_PIN_1) == 0) ; //single press
			}
			//PA13 >> connected external PDR
			if(MCAL_GPIO_ReadPIN(GPIOA, GPIO_PIN_13) == 1) //multi press
			{
				MCAL_GPIO_TogglePIN(GPIOB, GPIO_PIN_13);

			}
			char i ;
			for (i=0 ; i <200 ;i++);
		}*/
	clock_init();
	app_init();
	unsigned char key_pressed;
	uint8_t sevenSegment[] = {ZERO,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,ZERO};
	uint8_t lcd[] = {'0','1','2','3','4','5','6','7','8','9','0'};
	uint8_t i ;
	for (i=0 ; i<11 ; i++ )
	{
	MCAL_GPIO_WritePORT(GPIOB, sevenSegment[i] << 9);
	LCD_send_char(lcd[i]);
	delay_function_ms(100);
	}
	KEYPAD_init();
	LCD_clear_screen();
	LCD_send_string("KEYPAD IS READY!");
	delay_function_ms(100);
	LCD_clear_screen();

	//LCD_send_string("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!@#$%^&*()-_=+[{]}");
	//delay_function_ms(500);
	//LCD_clear_screen();
	while (1){

		/*	LCD_clear_screen();
		delay_function_ms(500);
		LCD_set_position(1,0);
		LCD_send_string("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!@#$%^&*()-_=+[{]}");
		delay_function_ms(500);
		LCD_clear_screen();*/

		key_pressed = KEYPAD_read_button();
		switch(key_pressed){
		case 'A':
			break;
		case 'C':
			LCD_clear_screen();
			break;
		default:
			LCD_send_char(key_pressed);
			break;
		}

	}

}
