/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stm32f103x6.h"
#include "Stm32F103C6_GPIO_Driver.h"
#include "Stm32F103C6_EXTI_Driver.h"

#include "lcd.h"
#include "keypad.h"
#include "sevensegment.h"

uint32_t IRQ_Flag = 0	;


void EXTI9_CallBack(void)
{
	LCD_clear_screen();
	MCAL_GPIO_TogglePIN(GPIOA , GPIO_PIN_11);
	IRQ_Flag	=	1	;
	LCD_send_string("IRQ EXTI9 happened _|- ");
	delay_function_ms(100);
}

void clock_init()
{
	//GPIOA ,GPIOB & AFIO CLOCK ENABLE
	RCC_GPIOA_CLCK_EN()	;
	RCC_GPIOB_CLCK_EN()	;
	RCC_AFIO_CLK_EN()	;


}
void app_init()
{
	s_LCD_Config_t LCD_config;
	LCD_config.e_DispCtrl	= ON_DISP | ON_BLINK | ON_CURSOR ;
	LCD_config.e_EntryMode	= NOSHIFT_INCREMENT;
	LCD_config.e_FuncSet	= EIGHT_BIT_MODE_2LINE_10DOTS;
	LCD_init(&LCD_config);
	//sevensegment_init();
	//KEYPAD_init();
}

void EXTI_init()
{

	EXTI_PINCNFG_t pinCnfg;
	pinCnfg.EXTI_PIN	= EXTI9_PB9 			;
	pinCnfg.Trigger		= EXTI_TRIGGER_RISING	;
	pinCnfg.IRQ_EN		= IRQ_ENABLE			;
	pinCnfg.P_CallBack	= EXTI9_CallBack		;
	MCAL_EXTI_GPIO_Init(&pinCnfg) 				;
}



void GPIO_init()
{
	GPIO_PinConfig_t pinCnfg ;
	pinCnfg.GPIO_PinNumber		=	GPIO_PIN_11			;
	pinCnfg.GPIO_Mode			=	GPIO_MODE_OUT_PP	;
	pinCnfg.GPIO_Output_Speed	=	GPIO_SPEED_10M		;
	MCAL_GPIO_Init(GPIOA, &pinCnfg)						;

}


int main(void)
{
	clock_init();
	app_init();
	GPIO_init();
	EXTI_init();
	IRQ_Flag	=	1	;
	while (1)
	{
		if(IRQ_Flag)
		{
			LCD_clear_screen();
			delay_function_ms(100);
			LCD_send_string("HELLO EMBEDDED  SYSTEMS :)");
			delay_function_ms(500);
			IRQ_Flag	=	0	;
		}



	}






}
