/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "Stm32F103C6_GPIO_Driver.h"

void clock_init()
{
	//GPIOA clock enable
	GPIOA_CLCK_EN();
	//GPIOB clock enable
	GPIOB_CLCK_EN();

}
void GPIO_init(){
	GPIO_PinConfig_t* pinCnfg = NULL;
	//for PA pin1 to be floating input
	pinCnfg->GPIO_PinNumber = GPIO_PIN_1;
	pinCnfg->GPIO_Mode = GPIO_MODE_FLO_IN;
	MCAL_GPIO_Init(GPIOA,pinCnfg);

	//for PB pin1 to be output push/pull mode
	pinCnfg->GPIO_PinNumber = GPIO_PIN_1;
	pinCnfg->GPIO_Mode = GPIO_MODE_OUT_PP;
	pinCnfg->GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB,pinCnfg);
	//for PA pin13 to be floating input
	pinCnfg->GPIO_PinNumber = GPIO_PIN_13;
	pinCnfg->GPIO_Mode = GPIO_MODE_FLO_IN;
	MCAL_GPIO_Init(GPIOA,pinCnfg);
	//for PB pin13 to be output push/pull mode
	pinCnfg->GPIO_PinNumber = GPIO_PIN_13;
	pinCnfg->GPIO_Mode = GPIO_MODE_OUT_PP;
	pinCnfg->GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB,pinCnfg);

}

void my_wait(int x)
{
	unsigned int i,j;
	for (i=0 ; i<x ;i++)
		for (j=0 ; j<255 ;j++);

}
int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
		{
			//PA1 >> connected external PUR
			if(MCAL_GPIO_ReadPIN(GPIOA, GPIO_PIN_1) == 0) //press
			{
				MCAL_GPIO_TogglePIN(GPIOB, GPIO_PIN_1);
				while(MCAL_GPIO_ReadPIN(GPIOA, GPIO_PIN_1) == 0) ; //single press
			}
			//PA13 >> connected external PDR
			if(MCAL_GPIO_ReadPIN(GPIOA, GPIO_PIN_13) == 1) //multi press
			{
				MCAL_GPIO_TogglePIN(GPIOB, GPIO_PIN_13);

			}
			char i ;
			for (i=0 ; i <200 ;i++);
		}

}
