/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
//GPIOA
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL *((volatile uint32_t*)(GPIOA_BASE+0x00))
#define GPIOA_CRH *((volatile uint32_t*)(GPIOA_BASE+0x04))
#define GPIOA_IDR *((volatile uint32_t*)(GPIOA_BASE+0x08))
//GPIOB
#define GPIOB_BASE 0x40010C00
#define GPIOB_CRL *((volatile uint32_t*)(GPIOB_BASE+0x00))
#define GPIOB_CRH *((volatile uint32_t*)(GPIOB_BASE+0x04))
#define GPIOB_ODR *((volatile uint32_t*)(GPIOB_BASE+0x0C))

//RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *((volatile uint32_t*)(RCC_BASE+0x18))


void clock_init(){
	//GPIOA enable clock
	RCC_APB2ENR |= (1<<2);
	//GPIOB enable clock
	RCC_APB2ENR |= (1<<3);

}
void GPIO_init(){

	GPIOA_CRL &= 0x0;
	GPIOB_CRL &= 0x0;
	GPIOA_CRH &= 0x0;
	GPIOB_CRH &= 0x0;
	//for PA pin1 to be floating input
	//default
	GPIOA_CRL |= 1<<6;
	//for PB pin1 to be output push/pull mode
	GPIOB_CRL |= (1<<4);
	//GPIOB_CRL |= (0b01<<4);
	GPIOB_ODR |= (1<<1);


	////for PA pin13 to be floating input
	//default
	GPIOA_CRH |= 1<<22;
	//for PB pin13 to be output push/pull mode
	GPIOB_CRH |= (1<<20);
	GPIOB_ODR |= (1<<13);
}


void my_wait(int x)
{
	unsigned int i,j;
	for (i=0 ; i<x ;i++)
		for (j=0 ; j<255 ;j++);

}
int main(){
	clock_init();
	GPIO_init();
	while(1)
	{
		//PA1 >> connected external PUR
		if(((GPIOA_IDR & (1<<1)) >> 1) == 0) //press
		{
			GPIOB_ODR ^= (1<<1);
			while(((GPIOA_IDR & (1<<1)) >> 1) == 0); //single press
		}
		//PA13 >> connected external PDR
		if(((GPIOA_IDR & (1<<13)) >> 13) == 1) //multi press
		{
			GPIOB_ODR ^= (1<<13);

		}


		my_wait(1); //delay
	}


	return 0;
}
