/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "../MCAL/GPIO/INCS/stm32f103x6_GPIO.h"
#include "../MCAL/EXTI/INCS/stm32f103x6_EXTI.h"

void callbackFunc()
{
	MCAL_GPIO_TogglePIN(GPIOA ,GPIO_PIN_8) ;
}
void GPIO_init()
{
	GPIOA_CLCK_EN();
	GPIO_PinConfig_t PINCNFG ;
	PINCNFG.GPIO_Mode = GPIO_MODE_OUT_PP ;
	PINCNFG.GPIO_PinNumber = GPIO_PIN_8 ;
	PINCNFG.GPIO_Speed = GPIO_SPEED_10M ;
	PINCNFG.GPIO_Direction = OUTPUT ;
	MCAL_GPIO_init(GPIOA,&PINCNFG);

}

void EXTI_init()
{
	EXTI_PinConfig_t PINCNFG ;
	PINCNFG.EXTI_Direction = INPUT ;
	PINCNFG.EXTI_Edge = EXTI_RI_FA ;
	PINCNFG.EXTI_Line = EXTI4 ;
	PINCNFG.EXTI_Mode = EXTI_MODE_IN_FLO ;
	PINCNFG.P_CallBack = callbackFunc ;
	PINCNFG.EXTI_Speed = EXTI_SPEED_10M ;
	MCAL_EXTI_init(&PINCNFG,GPIOA) ;

	PINCNFG.EXTI_Direction = INPUT ;
	PINCNFG.EXTI_Edge = EXTI_RI_FA ;
	PINCNFG.EXTI_Line = EXTI1 ;
	PINCNFG.EXTI_Mode = EXTI_MODE_IN_FLO ;
	PINCNFG.P_CallBack = callbackFunc ;
	PINCNFG.EXTI_Speed = EXTI_SPEED_10M ;
	MCAL_EXTI_init(&PINCNFG,GPIOA) ;







}


int main(void)
{

	//GPIO CNFGS
	GPIO_init() ;
	AFIO_CLCK_EN();
	EXTI_init();

	MCAL_EXTI_Deinit(EXTI1,GPIOA);

	while(1);
	return 0;
}










