/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stdint.h"
//RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *((volatile uint32_t*)(RCC_BASE+0x18))
//GPIO
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *((volatile uint32_t*)(GPIOA_BASE+0x04))
#define GPIOA_CRL *((volatile uint32_t*)(GPIOA_BASE+0x00))
#define GPIOA_ODR *((volatile uint32_t*)(GPIOA_BASE+0x0c))

//AFIO
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1 *((volatile uint32_t*)(AFIO_BASE+0x08))
//EXTI
#define EXTI_BASE 0x40010400
#define EXTI_IMR *((volatile uint32_t*)(EXTI_BASE+0x00))
#define EXTI_RTSR *((volatile uint32_t*)(EXTI_BASE+0x08))
#define EXTI_PR *((volatile uint32_t*)(EXTI_BASE+0x14))
//NVIC
#define NVIC_ISER0 *((volatile uint32_t*)(0xE000E100))


void GPIO_init()
{
	//GPIOA pin 13 >> out
	GPIOA_CRH &=0xFF0FFFFF;
	GPIOA_CRH |=0x00200000;
	//GPIOA pin0 >> floating input
	GPIOA_CRL &=0xFFFFFF0F;
	GPIOA_CRL |= (1<<2);
}
void clock_init()
{
	//Enable clock for GPIOA
	RCC_APB2ENR |=(1<<2);
	//Enable clock for AFIO
	RCC_APB2ENR |=(1<<0);

}



int main(void)
{
	clock_init();
	GPIO_init();
	//EXTI0 config to PORTA0
	AFIO_EXTICR1 = 0; //don't need it (set by 0000 by default
	//ENABLE EXTI LINE0 (mask 1)
	EXTI_IMR |=(1<<0);
	//Enable rising edge
	EXTI_RTSR |=(1<<0);
	//enable NVIC line0 (from IVT it EXTI 0 is connected to vector 6 )
	//So we enable vector 6 in NVIC (FTOM CPU TRM)
	NVIC_ISER0 |= (1<<6);
	while(1);
}


void EXTI0_IRQHandler(void)
{
	//IRQ is happened >> PORTA_pin0 >> Rising edge
	//toggle PA pin13
	GPIOA_ODR ^= (1UL<<13);
	//clear pinding request for line 0
	EXTI_PR |=(1<<0); //w1c
}
