/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "stm32f103x6.h"
#include "Stm32F103C6_GPIO_Driver.h"
#include "Stm32F103C6_EXTI_Driver.h"
#include "Stm32F103C6_USART_Driver.h"
#include "Stm32F103C6_SPI_Driver.h"
#include "Stm32F103C6_I2C_Driver.h"
#include "I2C_EEPROM.h"



void clock_init()
{
	//GPIOA ,GPIOB & AFIO CLOCK ENABLE
	RCC_GPIOA_CLCK_EN()	;
	RCC_GPIOB_CLCK_EN()	;
	RCC_AFIO_CLK_EN()	;
}


int main(void)
{
	clock_init();


		uint8_t ch1[]={0x1,0x2,0x3,0x4,0x5,0x6,0x7};
		uint8_t ch2[7]={0};
		EEPROM_init();
		EEPROM_write_Nbytes(0xAF, ch1, 7);
		EEPROM_read_byte(0xAF, ch2, 7);

		//TEST CASE 2
		ch1[0]=0xA;
		ch1[1]=0xB;
		ch1[2]=0xC;
		ch1[3]=0xD;
		EEPROM_write_Nbytes(0xFFF, ch1, 4);
		EEPROM_read_byte(0xFFF, ch2, 4);


	while (1)
	{


	}
}









