/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "../MCAL/GPIO/INCS/stm32f103x6_GPIO.h"



void GPIO_init()
{

	GPIOA_CLCK_EN();
	GPIO_PinConfig_t PINCNFG ;
	PINCNFG.GPIO_Mode = GPIO_MODE_IN_FLO ;
	PINCNFG.GPIO_PinNumber = GPIO_PIN_5 ;
	MCAL_GPIO_init(GPIOA,&PINCNFG);


	PINCNFG.GPIO_Mode = GPIO_MODE_OUT_PP ;
	PINCNFG.GPIO_PinNumber = GPIO_PIN_8 ;
	PINCNFG.GPIO_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_init(GPIOA,&PINCNFG);


}




int main(void)
{


	GPIO_init();
	while (1)
	{

		if( MCAL_GPIO_ReadPIN(GPIOA ,GPIO_PIN_5) == 1 )
		{
			MCAL_GPIO_WritePIN(GPIOA, GPIO_PIN_8, 1) ;
		}

		int i ;
		for (i = 0 ; i<50000 ; i++) ;

		if( MCAL_GPIO_ReadPIN(GPIOA ,GPIO_PIN_5) == 0 )
		{
			MCAL_GPIO_WritePIN(GPIOA, GPIO_PIN_8, 0) ;
		}
		for (i = 0 ; i<50000 ; i++) ;

	}


	return 0;
}










