/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "FreeRTOS.h"
#include "Stm32F103C6_GPIO_Driver.h"
#include "task.h"
#include "queue.h"
#include "FreeRTOSConfig.h"
#include "stdint.h"

//===============HANDLERs==================

TaskHandle_t vTaskMasterHandel 	= NULL ;
TaskHandle_t vTaskSlaveHandel 	= NULL ;
QueueHandle_t xQueueHandel 		= NULL ;

//tasks prototypes


void vTaskMasterHandler( void *par);
void vTaskSlaveHandler( void *par);





void HW_init(void)
{
	//LED PIN AS OUTPUT  >> PC13
	GPIO_PinConfig_t PINCNFG ;
	PINCNFG.GPIO_PinNumber		= GPIO_PIN_13		;
	PINCNFG.GPIO_Mode			= GPIO_MODE_OUT_PP	;
	PINCNFG.GPIO_Output_Speed	= GPIO_SPEED_10M	;
	MCAL_GPIO_Init(GPIOC, &PINCNFG)					;


}

void CLK_EN(void)
{
	RCC_GPIOC_CLCK_EN();
}


int main(void)
{
	CLK_EN();
	HW_init();
	//Tasks Creation
	xTaskCreate(vTaskMasterHandler, "Master generates commands",128, NULL, 1, &vTaskMasterHandel);
	xTaskCreate(vTaskSlaveHandler, "Slave executes commands",128, NULL, 2, &vTaskSlaveHandel);
	xQueueHandel = xQueueCreate( 10,sizeof(uint8_t) );
	vTaskStartScheduler();

	while (1)
	{

	}
	return 0 ;
}



void vTaskMasterHandler( void *pvParameters)
{

	uint8_t ONCommand	=	1 ;
	uint8_t OFFCommand	=	0 ;
	while (1)
	{
		xQueueSend(xQueueHandel,&OFFCommand,(TickType_t)5);
		vTaskDelay(15);
		xQueueSend(xQueueHandel,&ONCommand,(TickType_t)5);
		vTaskDelay(15);
	}

}
void vTaskSlaveHandler( void *pvParameters)
{
	uint8_t commandReceive = 0 ;
	while (1)
	{
		if( xQueueReceive(xQueueHandel, &commandReceive, (TickType_t)5) == pdTRUE )
		{

			if(commandReceive == 0 )
			{
				MCAL_GPIO_WritePIN(GPIOC, GPIO_PIN_13, 0);

			}
			else if (commandReceive == 1 )
			{
				MCAL_GPIO_WritePIN(GPIOC, GPIO_PIN_13, 1);

			}
		}
		vTaskDelay(15);
	}

}





