/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "FreeRTOS.h"
#include "Stm32F103C6_GPIO_Driver.h"
#include "task.h"
#include "semphr.h"
#include "FreeRTOSConfig.h"
#include "stdint.h"

//===============HANDLERs==================

TaskHandle_t vTaskButtonHandel = NULL ;
TaskHandle_t vTaskLedHandel = NULL ;
SemaphoreHandle_t xSemaphore = NULL ;

//tasks prototypes


void vTaskButtonHandler( void *par);
void vTaskLedHandler( void *par);


uint8_t	Button_Curr_State = 0 ;
uint8_t	Button_Prev_State = 0 ;


void HW_init(void)
{
	//LED PIN AS OUTPUT  >> PC13
	GPIO_PinConfig_t PINCNFG ;
	PINCNFG.GPIO_PinNumber		= GPIO_PIN_13		;
	PINCNFG.GPIO_Mode			= GPIO_MODE_OUT_PP	;
	PINCNFG.GPIO_Output_Speed	= GPIO_SPEED_10M	;
	MCAL_GPIO_Init(GPIOC, &PINCNFG)					;

	//Button Pin as input >> PC
	PINCNFG.GPIO_PinNumber		= GPIO_PIN_15		;
	PINCNFG.GPIO_Mode			= GPIO_MODE_IN_PD	;
	MCAL_GPIO_Init(GPIOC, &PINCNFG)					;

}

void CLK_EN(void)
{
	RCC_GPIOC_CLCK_EN();
}


int main(void)
{
	CLK_EN();
	HW_init();




	//Tasks Creation
	xTaskCreate(vTaskButtonHandler, "Button Handler",128, NULL, 1, &vTaskButtonHandel);
	xTaskCreate(vTaskLedHandler, "LED Handler",200, NULL, 2, &vTaskLedHandel);
	xSemaphore = xSemaphoreCreateBinary();


	vTaskStartScheduler();




	while (1)
	{

	}
	return 0 ;
}



void vTaskButtonHandler( void *pvParameters)
{
	//Monitoring the button's state
	while (1)
	{
		Button_Curr_State = MCAL_GPIO_ReadPIN(GPIOC, GPIO_PIN_15);

		//If there is a change in the state of the button this function would release(give) the semaphore
		if(Button_Curr_State != Button_Prev_State)
		{
			xSemaphoreGive(xSemaphore);
		}

		Button_Prev_State = Button_Curr_State;

		vTaskDelay(25);

	}

}
void vTaskLedHandler( void *pvParameters)
{
	while (1)
		{
			if(xSemaphoreTake(xSemaphore,(TickType_t)5)==pdTRUE)
			{

				if(Button_Curr_State == 1 )
				{
					MCAL_GPIO_WritePIN(GPIOC, GPIO_PIN_13, 1);
				}
				else
				{
					MCAL_GPIO_WritePIN(GPIOC, GPIO_PIN_13, 0);

				}

			}
			vTaskDelay(5);
		}

}





